// token.h - dcc 词法单元定义
#ifndef DCC_TOKEN_H
#define DCC_TOKEN_H

#include <string>

namespace dcc {

enum TokenKind {
	TOK_EOF,
	TOK_IDENT,		// 标识符
	TOK_NUMBER,		// 数字字面量（十进制/十六进制/八进制）
	TOK_FLOATLIT,	// 浮点字面量（1.5 / 1e3 / 2.5f）
	TOK_CHARLIT,	// 字符字面量 'a'
	TOK_STRING,		// 字符串字面量 "abc"
	// 关键字
	TOK_INT, TOK_SHORT, TOK_LONG, TOK_FLOAT, TOK_DOUBLE, TOK_CHAR, TOK_BOOL, TOK_VOID, TOK_SIGNED, TOK_UNSIGNED,
	TOK_CONST, TOK_SIZEOF, TOK_INTERRUPT,
	TOK_STRUCT, TOK_UNION, TOK_ENUM, TOK_TYPEDEF,
	TOK_EXTERN, TOK_STATIC, TOK_INLINE, TOK_ASM, TOK_RETURN, TOK_IF, TOK_ELSE, TOK_WHILE,
	TOK_FOR, TOK_BREAK, TOK_CONTINUE,
	// 运算符/分隔符
	TOK_LPAREN, TOK_RPAREN, TOK_LBRACE, TOK_RBRACE, TOK_LBRACKET, TOK_RBRACKET,
	TOK_SEMI, TOK_COMMA, TOK_DOT, TOK_ELLIPSIS, TOK_ARROW,
	TOK_ASSIGN,				// =
	TOK_PLUS, TOK_MINUS, TOK_STAR, TOK_SLASH, TOK_PERCENT,
	TOK_EQ, TOK_NE, TOK_LT, TOK_LE, TOK_GT, TOK_GE,
	TOK_ANDAND, TOK_OROR, TOK_NOT, TOK_AND, TOK_OR, TOK_XOR, TOK_TILDE,
	TOK_SHL, TOK_SHR,
	TOK_INC, TOK_DEC,		// ++ --
	TOK_QUESTION, TOK_COLON,
	TOK_PLUS_ASSIGN, TOK_MINUS_ASSIGN, TOK_STAR_ASSIGN, TOK_SLASH_ASSIGN,
	TOK_PERCENT_ASSIGN, TOK_AND_ASSIGN, TOK_OR_ASSIGN, TOK_XOR_ASSIGN,
	TOK_SHL_ASSIGN, TOK_SHR_ASSIGN,
};

struct Token {
	TokenKind kind;
	std::string text;		// 原文
	long long ival;			// 数字/字符值
	double fval;			// 浮点字面量值
	std::string sval;		// 字符串内容
	int line;				// 行号
};

} // namespace dcc

#endif
